; PlatformIO Project Configuration File
;
; GPIO high-drive (high-current) output demo for XIAO nRF54LM20A/B.
; Drives D0 (P1.00) as a high-drive output (NRF_GPIO_DRIVE_H0H1).

[env:seeed-xiao-nrf54lm20a]
platform = https://github.com/Seeed-Studio/platform-seeedboards.git
framework = zephyr
board = seeed-xiao-nrf54lm20a
monitor_speed = 115200

[env:seeed-xiao-nrf54lm20b]
platform = https://github.com/cumin777/platform-seeedboards.git#seeed_nrf54lm20b_xiao_α_test
framework = zephyr
board = seeed-xiao-nrf54lm20b
monitor_speed = 115200
