; PlatformIO Project Configuration File
;
; BMP280 Sensor Demo for XIAO nRF54LM20A
; Note: Zephyr uses the built-in BME280 driver, which also supports BMP280.

[env:seeed-xiao-nrf54lm20a]
platform = Seeed Studio
framework = zephyr
board = seeed-xiao-nrf54lm20a
monitor_speed = 115200

; upload_protocol = jlink

[env:seeed-xiao-nrf54lm20b]
platform = https://github.com/cumin777/platform-seeedboards.git#seeed_nrf54lm20b_xiao_α_test
framework = zephyr
board = seeed-xiao-nrf54lm20b
monitor_speed = 115200
