; PlatformIO Project Configuration File
;
; ADC demo for XIAO nRF54LM20A
;
; SPDX-License-Identifier: Apache-2.0

[env:seeed-xiao-nrf54lm20a]
platform = file:///disk/E/git_file/platform-seeedboards
framework = zephyr
board = seeed-xiao-nrf54lm20a
monitor_speed = 115200

[env:seeed-xiao-nrf54lm20b]
platform = https://github.com/cumin777/platform-seeedboards.git#seeed_nrf54lm20b_xiao_α_test
framework = zephyr
board = seeed-xiao-nrf54lm20b
monitor_speed = 115200
