#
# Copyright (c) 2026 Seeed Technology Co., Ltd.
#
# SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
#

# DTM uses the XIAO exposed hardware serial pins through uart21.
CONFIG_CONSOLE=n
CONFIG_UART_CONSOLE=n
