#
# Copyright (c) 2026 Seeed Technology Co., Ltd.
#
# SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
#

# DTM uses the XIAO exposed hardware serial pins through uart21.
CONFIG_CONSOLE=n
CONFIG_UART_CONSOLE=n

# Keep this DTM build on the standard 2-wire UART path.
CONFIG_USB_DEVICE_STACK=n
CONFIG_USB_DEVICE_STACK_NEXT=n
CONFIG_USB_CDC_ACM=n
