; PlatformIO Project Configuration File

[env:seeed-xiao-nrf54l15]
platform = https://github.com/Seeed-Studio/platform-seeedboards.git
framework = zephyr
board = seeed-xiao-nrf54l15
monitor_speed = 115200

[env:seeed-xiao-nrf54lm20a]
platform = https://github.com/Seeed-Studio/platform-seeedboards.git
framework = zephyr
board = seeed-xiao-nrf54lm20a
platform_packages =
  platformio/toolchain-gccarmnoneeabi@~1.90201.0
monitor_speed = 115200

[env:seeed-xiao-nrf54lm20b]
platform = https://github.com/cumin777/platform-seeedboards.git#seeed_nrf54lm20b_xiao_α_test
framework = zephyr
board = seeed-xiao-nrf54lm20b
platform_packages =
  platformio/toolchain-gccarmnoneeabi@~1.90201.0
monitor_speed = 115200
