; PlatformIO Project Configuration File
;   08-UARTR-back: back-pad UART (uart20) test for XIAO nRF54LM20B

[env:seeed-xiao-nrf54lm20b]
platform = https://github.com/cumin777/platform-seeedboards.git#seeed_nrf54lm20b_xiao_α_test
framework = zephyr
board = seeed-xiao-nrf54lm20b
monitor_speed = 1000000
