CONFIG_BOOT_SIGNATURE_KEY_FILE="D:/workspace/ncs/v3.3.0/bootloader/mcuboot/root-ed25519.pem"

CONFIG_ROM_START_OFFSET=0
CONFIG_BOOT_MAX_IMG_SECTORS=256

CONFIG_PM=n

CONFIG_BOOT_BANNER=n
CONFIG_NCS_BOOT_BANNER=n
CONFIG_BOOT_ENCRYPT_IMAGE=n
CONFIG_BOOT_SWAP_SAVE_ENCTLV=n
CONFIG_BOOT_UPGRADE_ONLY=n
CONFIG_BOOT_WATCHDOG_FEED=n
CONFIG_BOOT_VALIDATE_SLOT0=y

CONFIG_FLASH=y
CONFIG_FPROTECT=y
CONFIG_SPI_NOR=n

CONFIG_CBPRINTF_NANO=y
CONFIG_PICOLIBC=y
CONFIG_COMMON_LIBC_MALLOC_ARENA_SIZE=0

CONFIG_CLOCK_CONTROL=n
CONFIG_NRF_GRTC_START_SYSCOUNTER=n

CONFIG_SERIAL=n
CONFIG_CONSOLE=n
CONFIG_UART_CONSOLE=n
CONFIG_PRINTK=n
CONFIG_USE_SEGGER_RTT=n

CONFIG_LTO=y
CONFIG_ISR_TABLES_LOCAL_DECLARATION=y

CONFIG_RESET_ON_FATAL_ERROR=n
